### DISCUSSION TITLE
How to get the archive filename in the hook?

### DISCUSSION THREAD

**Discussion by lionello** [goreleaser/goreleaser-pro#25] [Q&A]
I've checked all available template variables, but can't seem to find the name of the final archive in the hook. In particular, I see `.ArtifactExt`, `.ArtifactName`, `.ArtifactPath`, and `.Artifacts`, but all of these seem to relate to the contents of the archive, not the archive itself.

```
archives:
  - id: archive
    hooks:
      after:
        - echo '{{ printf "%#v" . }}'
        - echo '{{ printf "%#v" (index .Artifacts 0) }}'
        - echo '{{ printf "%#v" (index .Artifacts 1) }}'
```
