### DISCUSSION TITLE
Github Action to Create the MSI file

### DISCUSSION THREAD

**Discussion by vipinvkmenon** [goreleaser/goreleaser-pro#30] [Q&A]
The goreleaser has been a good tool for our packaging solutions, and we want to expand its usage. Specifically, we are evaluating the goreleaser-pro for building MSI packages.

I'm trying to create a github action to run the go-releaser pro to build MSI files, and we are stuck.

Here is my sample configuration:

```goreleaser.yaml
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - windows
    goarch:
      - amd64
    binary: "testcliv{{ .Version }}"
archives:
  - formats: ["binary"]
    name_template: "testcli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

msi:
- wxs: install.wxs
  replace: true
  mod_timestamp: "{{ .CommitTimestamp }}"
  version: v4
 
```
A GH action to test creating a build.

```yaml
name: build msi

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build-msi:
    runs-on: windows-latest 

    steps:
     # This prerequisite of having installed is not clear in the documentation. Is it needed? It doesn't work without this though 
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Install WiX
        run: dotnet tool install --global wix
       # --------
      - name: Get latest release tag
        id: latest_release
        shell: pwsh
        run: |
          $tag = (gh release list --limit 1 --repo "${{ github.repository }}" | Select-String -Pattern '^\S+' -AllMatches).Matches.Value
          echo "tag=$tag" >> $env:GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code at latest tag
        uses: actions/checkout@v4
        with:
          # ref: ${{ steps.latest_release.outputs.tag }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Generate product_code GUID
        id: guid
        shell: pwsh
        run: |
          $guid = [guid]::NewGuid().ToString().ToUpper()
          echo "PRODUCT_CODE={$guid}" >> $env:GITHUB_ENV

      - name: Build MSI only
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "v2.7.0"
          distribution: goreleaser-pro
          args: release --clean --snapshot --config=goreleaser-msi.yaml --timeout=60m
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          PRODUCT_CODE: ${{ env.PRODUCT_CODE }}

```
And the `install.wix` file itself. My assumption is, after `intall.wix` is sorted,  this setup should work.
Is this approach in the right direction/correct?

I have some queries regarding this feature:-

1) My initial understanding of the configuration documentation, it uses Wix toolset underneath. And also requires the `wix` configuration XML file. What are the advantages of building/configuring `MSI` packages using goreleaser-pro over the alternative, say..` candle & light`? Is there a simpler configuration that is available as an alternative to a templated `wix` XML file?

2) In the [documentation](https://goreleaser.com/customization/msi/), it states: `On Windows, it'll try to use the candle and light binaries from the [Wix Toolkit](https://wixtoolset.org/) instead if schema is v3. It'll use Wix otherwise.` Does that mean it can also run on Linux environments? (Or can MSI packages only be built on Windows?)

3) Also, what is the latest version of `pro` available? is it `2.7.0-pro` or `2.9.0` ? But if I put `2.9.0` the gihub action fails stating `2.9.0-pro` not found.

4) Is there a working example/documentation of running goreleaser-pro to build msi in or something similar in `github actions` available? This would be highly appreciable.

5) Is the documentation for both `goreleaser` and `goreleaser-pro` the same? I felt like there were some differences in the flags between the OSS and pro edition..For E.G `--skip` flag.

Lookig forward to these answers and trying out the pro features soon :)

- Thanks
